version: 0.0.1.{build}
install:
- ps: >-
    mkdir -Force ".\.bootstrap\" | Out-Null

    Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\.bootstrap\dotnet-install.ps1"
    
    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
    
    .\.bootstrap\dotnet-install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR"
    
    $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
build_script:
- ps: >-
    dotnet restore

    dotnet --verbose build .\src\**\project.json
    